### ISSUE TITLE
What user is this using ?

### ISSUE THREAD

**Issue by crisp2u** [jenkinsci/docker-ssh-slave#16]
Guys,

I'm a bit confused, what user is this container running ? I see jenkins user added but it seems os running root.

Thanks

**Comment by bilke** [comment]
This confuses me too. @crisp2u is correct but I think that the container should be run as `jenkins`-user. This would be inline with the `jenkins/jnlp-slave` image. Simply switching the user does not work as `setup-sshd` required root rights.
