### ISSUE TITLE
Is this repository maintained?

### ISSUE THREAD

**Issue by LJBD** [jenkinsci/docker-ssh-slave#19]
The last commits are a year old and there are some hanging PRs. Is this repository still maintained? If not, can we expect a different image for a Jenkins SSH slave? Or is the JNLP slave the only way to go?

**Comment by oleg-nenashev** [comment]
CC @ndeloof @carlossg

**Comment by carlossg** [comment]
I don't have permissions on this repo

**Comment by oleg-nenashev** [comment]
I have permissions as Jenkins org admin, but I would like to get a response from the maintainer first.

**Comment by ndeloof** [comment]
feel free to take over

**Comment by oleg-nenashev** [comment]
OK, I claim it co-maintained by me and other @jenkinsci/core members until somebody steps in to take formal ownership.

**Comment by oleg-nenashev** [comment]
All Core team members got write permissions for now. @carlossg you should also have them now

**Comment by oleg-nenashev** [comment]
BTW, I confirm that the CI flow is alive. So new deployments of `latest` will happen on-merge.
