### ISSUE TITLE
Advice needed custom files in /home/jenkins

### ISSUE THREAD

**Issue by phreakadelle** [jenkinsci/docker-ssh-slave#20]
Hey. Maybe i got something completly wrong but i would like to build my own custom image and using this one as a parent. In my customization i would like to install the AWS CLI (and the .aws/credentials file) and also a .docker/config.json file inside the /home/jenkins folder. As /home/jenkins is a volume, i cannot modify this folder as changes are not applied.

How can i place files in /home/jenkins or is the approach wrong? I would like to have an advice on how to pass the login details etc. to my Jenkins Agent. Help is really appreciated.

```
FROM jenkins/ssh-slave

RUN curl -sSL https://get.docker.com/ | sh
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk python python-pip && \
    pip install awscli --upgrade && \
    apt-get clean -y && rm -rf /var/lib/apt/lists/* && \
    mkdir /home/jenkins/.aws/ && \
    mkdir /home/jenkins/.docker && \
    usermod -aG docker jenkins
    
COPY id_rsa id_rsa.pub known_hosts /home/jenkins/.ssh/
COPY credentials /home/jenkins/.aws/
COPY config.json /home/jenkins/.docker/
```

**Comment by DouglasRoyds** [comment]
Yes, as you have discovered, "[If any build steps change the data](https://docs.docker.com/engine/reference/builder/#volume) within the volume after it has been declared, those changes will be discarded."

I'd suggest you provide your own entrypoint script that copies your files into place, then invokes the  parent `setup-sshd` script with the correct parameters.

**Comment by oleg-nenashev** [comment]
Please feel free to reopen if this is still actual
