### ISSUE TITLE
Is there a docker ssh agent for windows container?

### ISSUE THREAD

**Issue by BlueAndi** [jenkinsci/docker-ssh-slave#29]
Does anybody know whether a docker ssh agent for windows container exists?

**Comment by oleg-nenashev** [comment]
I doubt. CC @slide who is working on Windows images for agents

**Comment by BlueAndi** [comment]
Thanks Oleg, lets hope @slide has something to share. :-)

**Comment by slide** [comment]
See https://github.com/jenkinsci/docker-ssh-slave/pull/27

**Comment by BlueAndi** [comment]
@slide Thanks, I will check.
