### ISSUE TITLE
Why are there so many volumes defined

### ISSUE THREAD

**Issue by slomo** [jenkinsci/docker-ssh-slave#30]
This is more a question than an issue: Why are the so many volmues defined in this image. To my understanding the slave is / should be state less. Hence keeping tmp, var/tmp and jenkins home  between deployments doesn't make sense. Or is it an optimisation because those locations are written and read frequently hence should be more performant than overlay fs.

**Comment by MarkEWaite** [comment]
The docker image does not mandate that the image must be stateless.  As an example, a long-lived docker-ssh-slave image is a good way for me to test specific agent configuration (Debian 9 with OpenJDK 8), whether or not the image is long-lived.

Have you encountered issues due to the volume definitions or was this purely a question of technical interest?

**Comment by slomo** [comment]
I was mildly annoyed by having to hook up all those volumes in docker compose, otherwise it worked fine. Thanks for responding.

**Comment by PapaNappa** [comment]
Could this issue be re-considered?

I don’t see any benefit of using `VOLUME` in a Dockerfile. [Others think so as well](https://stackoverflow.com/questions/41935435/understanding-volume-instruction-in-dockerfile/62068396#62068396).

It only leads to surprisingly creating anonymous volumes.

The argument is: if I want my container to be stateless/ephemeral, why are volumes created anyway? If I want to keep state, I should explicitly mount it.
With simple `docker run --rm` this might not be an issue (anonymous volumes are removed), but in all other cases, anonymous volumes are not removed:
* `docker run` / `docker rm`
* `docker compose up` / `docker compose down`
* `docker stack deploy` / `docker stack rm` / `docker service update`

The result is that the list of anonymous volumes just grows bigger and bigger.
Once the user realizes the anonymous volumes, it might be very hard to figure out which volumes are *really* needed.

The workaround is to manually mount all listed volumes.
But you have to be aware of this issue. And you have to throw away the volumes later on if you want the container to start fresh, which is also manual work.

In my specific case, I use a named volume for JENKINS_AGENT_HOME, but I don’t see the reason why I would need to persist `/tmp`, `/run`, and `/var/run`.
