### ISSUE TITLE
Alpine versions of the images

### ISSUE THREAD

**Issue by krufab** [jenkinsci/docker-ssh-slave#34]
It would be useful to have also the alpine versions of the docker-ssh-slave images, similar to what we have for [docker-slave](https://hub.docker.com/r/jenkinsci/slave)
I have created the [jdk-8-alpine](https://github.com/krufab/docker-ssh-slave/tree/jdk8-alpine) and [jdk-13-alpine](https://github.com/krufab/docker-ssh-slave/tree/jdk13-alpine) versions and they seem to work.
I'd like to create a PR, but I don't know how to integrate the code in your workdlow (i.e. should I also modify the Makefile and the Jenkins? If so, how?).
If you can have a look at the code and give me some hints, I will update it and create a PR with code accodrding to your standards.

**Comment by krufab** [comment]
@slide

**Comment by slide** [comment]
Yes, we would need to update the makefile to support building two Linux variants (the current + Alpine). I would recommend looking at the jenkinsci/docker repo's makefile. It doesn't need to be that complex, but it can show you how the makefile might be modified for multiple target images.

**Comment by krufab** [comment]
Done. Here's the [PR](https://github.com/jenkinsci/docker-ssh-slave/pull/35)

**Comment by oleg-nenashev** [comment]
Thanks! the `master` branch tag is already available: https://hub.docker.com/repository/docker/jenkins/ssh-slave . We will have a tagged version once the new release is cut

**Comment by oleg-nenashev** [comment]
I'd guess Java 13/14 would be the next step (if needed). Please create a follow-up ticket or PR if you are interested to get it introduced in this repo
