### ISSUE TITLE
JDK11 Version of image

### ISSUE THREAD

**Issue by FireDrunk** [jenkinsci/docker-ssh-slave#36]
Are there any plans for a JDK-11 version of this image the same way there are tags for the jnlp-slave image?

If required, I can assist in creating a PR.

**Comment by oleg-nenashev** [comment]
If there is a pull request, we can definitely integrate it. No plans at the moment
CC @jenkinsci/java11-support

**Comment by oleg-nenashev** [comment]
I fixed the build automation in #40 . Now it should be produced automatically
