### ISSUE TITLE
why does this image has slave.jar ?

### ISSUE THREAD

**Issue by thomasleveil** [jenkinsci/docker-ssh-slave#4]
Isn't the Jenkins master going to copy over its own slave.jar anyway?
Aren't the requirements for a Jenkins ssh slave only to have Java and a ssh daemon running?

**Comment by nurupo** [comment]
It also doesn't check the hash of the slave.jar it downloaded with the hash of expected slave.jar...

**Comment by ydubreuil** [comment]
Right, it doesn't make sense as it's not up to date. It should be cleaned up. Initial reason to do that was to be able to use that image without SSH but only with a plain docker command.

**Comment by dduportal** [comment]
Just sent a PR for this: https://github.com/jenkinsci/docker-ssh-slave/pull/11

**Comment by oleg-nenashev** [comment]
@dduportal's changes were integrated ~1 year ago
