### ISSUE TITLE
Improve tests and align code with docker-slave/jnlp

### ISSUE THREAD

**Issue by krufab** [jenkinsci/docker-ssh-slave#47]
The code of the tests can be improved and should be aligned with the one in https://github.com/jenkinsci/docker-slave and https://github.com/jenkinsci/docker-jnlp-slave

**Comment by oleg-nenashev** [comment]
I suppose it is addressed by #48 and #49, right?

**Comment by krufab** [comment]
Yes, I think it can be closed

**Comment by oleg-nenashev** [comment]
Thanks again!
